StylesPath = .vale/styles
MinAlertLevel = suggestion

Packages = write-good

[*.md]
BasedOnStyles = Vale, write-good
Vocab = custom
# Ignore custom template chart shortcode blocks
BlockIgnores = (?s)({{<\s*chart\s*>}}.*?{{<\s*/chart\s*>}})
# Ignore all inline template tags between double curly braces
TokenIgnores = ({{.*?}})


