StylesPath = .vale/styles
MinAlertLevel = suggestion

Packages = write-good, Hugo

[*.md]
BasedOnStyles = Vale, write-good
Vocab = custom
# Ignore custom template chart shortcode blocks
BlockIgnores = (?s)({{<\s*chart\s*>}}.*?{{<\s*/chart\s*>}})

write-good.ThereIs = false
write-good.E-Prime = false
